# Generated by Django 4.2.7 on 2023-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_modelaleximg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
            ],
        ),
    ]
